version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"

  ui:
    image: python:3.10
    volumes:
      - ..:/app
    working_dir: /app/ui
    command: streamlit run app.py
    ports:
      - "8501:8501
